### ISSUE TITLE
Updates needed to Publication page

### ISSUE THREAD

**Issue by grettadarmstrong** [CEGRcode/cegrcode.github.io#2]
The lab's publication page should at least include links to the YEP manuscript and Nature's preferred link: https://rdcu.be/cgxhs to the full article online (if not all of the publications from 2020 and 2021). Under Box://03/03/4/4/ are all of the published articles with manuscripts, so it makes sense to highlight the "Best of...."
 
- http://pughlab.mbg.cornell.edu/publications.html
include detail from http://yeastepigenome.org/yep/aboutus)
- and put the DOI on the page https://www.nature.com/articles/s41586-021-03314-8

**Comment by owlang** [comment]
Links updated. Relevant commit and pull request are added above.
